/*
CREATE or replace TABLE SNOWFLAKE_CI_CD_POC.CI_CD_DEMO.CUSTOM
(
   JOB_NM VARCHAR
  ,CREATED_BY VARCHAR
)
*/
;insert into SNOWFLAKE_CI_CD_POC.CI_CD_DEMO.SNOWFLAKE_CI_CD_DEMO14 (JOB_NM,CREATED_BY)
values ('c','d');


insert into SNOWFLAKE_CI_CD_POC.CI_CD_DEMO.CUSTOM (JOB_NM,CREATED_BY)
values ('f','g');

insert into SNOWFLAKE_CI_CD_POC.CI_CD_DEMO.CUSTOM (JOB_NM,CREATED_BY)
values ('iii','hhh');
insert into SNOWFLAKE_CI_CD_POC.CI_CD_DEMO.CUSTOM (JOB_NM,CREATED_BY)
values ('kkkk','hhh');
insert into SNOWFLAKE_CI_CD_POC.CI_CD_DEMO.CUSTOM (JOB_NM,CREATED_BY)
values ('qqqq','hhwwwh');

insert into SNOWFLAKE_CI_CD_POC.CI_CD_DEMO.CUSTOM (JOB_NM,CREATED_BY)
values ('qqqq','yyy');
insert into SNOWFLAKE_CI_CD_POC.CI_CD_DEMO.CUSTOM (JOB_NM,CREATED_BY)
insert into SNOWFLAKE_CI_CD_POC.CI_CD_DEMO.CUSTOM (JOB_NM,CREATED_BY)
values ('rraa','rr')
