CREATE OR REPLACE PROCEDURE SF_SANDBOX_DB.SF_SANDBOX_SCHEMA.SP_SF_PLTFRM_CREATE_DATABASE_PROC("P_TENANT_ABRV" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
       DATABASE_NM VARCHAR DEFAULT '''';
       DB_SQL VARCHAR DEFAULT '''';
BEGIN
    DATABASE_NM := P_TENANT_ABRV||''_DB'';
    DB_SQL:= ''CREATE OR REPLACE DATABASE ''|| :DATABASE_NM;

    EXECUTE IMMEDIATE :DB_SQL;

    USE WAREHOUSE SF_SANDBOX_WH;
    USE DATABASE SF_SANDBOX_DB;
    USE SCHEMA SF_SANDBOX_SCHEMA;

    INSERT INTO TEMP_T_DATABASE(DATABASE_NAME, PRIMARY_TAG)
    SELECT  :DATABASE_NM, :P_TENANT_ABRV;

        
/*EXCEPTION
    WHEN OTHER THEN
      IS_ERROR := ''1'';
      JOB_LOG_DESCRIPTION := ''SQLCODE:'' || SQLCODE || '' SQLERRM:'' || SQLERRM || '' SQLSTATE:'' ||SQLSTATE;
      RETURN ARRAY_CONSTRUCT(:IS_ERROR,:JOB_LOG_DESCRIPTION)  ;
*/
RETURN ''DATABASE CREATED'';
END;
';
