--CREATE OR REPLACE DATABASE SF_SANDBOX_DB COMMENT = 'DB for Snowflake Admins';
--create schema SF_SANDBOX_SCHEMA;
--
--CREATE ROLE "SF_SANDBOX_ROLE" COMMENT = 'Role for Snowflake Admins';
--
--CREATE or replace WAREHOUSE SF_SANDBOX_WH WITH WAREHOUSE_SIZE = 'SMALL' WAREHOUSE_TYPE = 'STANDARD' 
--AUTO_SUSPEND = 300 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'ECONOMY';
--
--grant monitor, operate, usage on warehouse SF_SANDBOX_WH to role "SF_SANDBOX_ROLE";
--
--GRANT USAGE ON DATABASE SF_SANDBOX_DB TO ROLE SF_SANDBOX_ROLE;
--grant create schema on database SF_SANDBOX_DB  to role SF_SANDBOX_ROLE;
--
--
--GRANT ROLE "SF_SANDBOX_ROLE" TO USER PSINGH;
--GRANT ROLE "SF_SANDBOX_ROLE" TO USER PRADSR;
--GRANT ROLE "SF_SANDBOX_ROLE" TO USER DBHATT;
--show users;


create or replace TABLE SF_SANDBOX_DB.SF_SANDBOX_SCHEMA.T_ACCOUNT (
	ACCOUNT_ID NUMBER(38,0) NOT NULL autoincrement,
	ACCOUNT VARCHAR(16777216),
	EDITION VARCHAR(16777216),
	CLOUD VARCHAR(16777216),
	REGION VARCHAR(16777216),
	CREATED VARCHAR(16777216),
	LOCATOR VARCHAR(16777216),
	primary key (ACCOUNT_ID)
);

create or replace TABLE SF_SANDBOX_DB.SF_SANDBOX_SCHEMA.T_TENANT (
	ACCOUNT_ID NUMBER(38,0),
	TENANT_ID NUMBER(38,0) NOT NULL autoincrement,
	TENANT_NAME VARCHAR(16777216),
	CLIENT VARCHAR(16777216),
	TENANT_ABRV VARCHAR(16777216),
	ONBOARDING_DATE TIMESTAMP_NTZ(9),
	END_DATE TIMESTAMP_NTZ(9),
	BUSINESS_PURPOSE VARCHAR(16777216),
	T_APPROVER VARCHAR(16777216),
	CLOUD VARCHAR(16777216),
	IS_ACTIVE VARCHAR(16777216),
	primary key (TENANT_ID),
	foreign key (ACCOUNT_ID) references SF_SANDBOX_DB.SF_SANDBOX_SCHEMA.T_ACCOUNT(ACCOUNT_ID)
);




create or replace TABLE SF_SANDBOX_DB.SF_SANDBOX_SCHEMA.T_DATABASE (
	TENANT_ID NUMBER(38,0),
	DATABASE_ID NUMBER(38,0) NOT NULL autoincrement,
	DATABASE_NAME VARCHAR(16777216),
	PRIMARY_TAG VARCHAR(16777216),
	primary key (DATABASE_ID),
	foreign key (TENANT_ID) references SF_SANDBOX_DB.SF_SANDBOX_SCHEMA.T_TENANT(TENANT_ID)
);

create or replace TABLE SF_SANDBOX_DB.SF_SANDBOX_SCHEMA.T_RESOURCE_MONITOR (
	TENANT_ID NUMBER(38,0),
	RM_ID NUMBER(38,0) NOT NULL autoincrement,
	RM_NAME VARCHAR(16777216),
	LEVEL VARCHAR(16777216),
	CREDIT_LIMIT VARCHAR(16777216),
	FREQUENCY VARCHAR(16777216),
	START_TIME TIMESTAMP_NTZ(9),
	CLUSTER_SIZE VARCHAR(16777216),
	PRIMARY_TAG VARCHAR(16777216),
	primary key (RM_ID),
	foreign key (TENANT_ID) references SF_SANDBOX_DB.SF_SANDBOX_SCHEMA.T_TENANT(TENANT_ID)
);


create or replace TABLE SF_SANDBOX_DB.SF_SANDBOX_SCHEMA.T_ROLES (
	TENANT_ID NUMBER(38,0),
	ROLE_ID NUMBER(38,0) NOT NULL autoincrement,
	ROLE_NAME VARCHAR(16777216),
	primary key (ROLE_ID),
	foreign key (TENANT_ID) references SF_SANDBOX_DB.SF_SANDBOX_SCHEMA.T_TENANT(TENANT_ID)
);



create or replace TABLE SF_SANDBOX_DB.SF_SANDBOX_SCHEMA.T_USERS (
	TENANT_ID NUMBER(38,0),
	ROLE_ID NUMBER(38,0),
	USER_ID NUMBER(38,0) NOT NULL autoincrement,
	USER_NAME VARCHAR(16777216),
	EMAIL_ID VARCHAR(16777216),
	IS_PRIMARY VARCHAR(16777216),
	PRIMARY_TAG VARCHAR(16777216),
	primary key (USER_ID),
	foreign key (TENANT_ID) references SF_SANDBOX_DB.SF_SANDBOX_SCHEMA.T_TENANT(TENANT_ID),
	foreign key (ROLE_ID) references SF_SANDBOX_DB.SF_SANDBOX_SCHEMA.T_ROLES(ROLE_ID)
);


create or replace TABLE SF_SANDBOX_DB.SF_SANDBOX_SCHEMA.T_WAREHOUSE (
	TENANT_ID NUMBER(38,0),
	RM_ID NUMBER(38,0),
	WH_ID NUMBER(38,0) NOT NULL autoincrement,
	WAREHOUSE_NAME VARCHAR(16777216),
	WAREHOUSE_SIZE VARCHAR(16777216),
	TYPE VARCHAR(16777216),
	CLUSTER_SIZE VARCHAR(16777216),
	PRIMARY_TAG VARCHAR(16777216),
	primary key (WH_ID),
	foreign key (TENANT_ID) references SF_SANDBOX_DB.SF_SANDBOX_SCHEMA.T_TENANT(TENANT_ID),
	foreign key (RM_ID) references SF_SANDBOX_DB.SF_SANDBOX_SCHEMA.T_RESOURCE_MONITOR(RM_ID)
);
