
CREATE or replace TABLE SNOWFLAKE_CI_CD_POC.CI_CD_DEMO.SNOWFLAKE_CI_CD_DEMO16
(
   JOB_NM VARCHAR
  ,CREATED_BY VARCHAR
)
;

Insert into  SNOWFLAKE_CI_CD_POC.CI_CD_DEMO.SNOWFLAKE_CI_CD_DEMO11 (JOB_NM,CREATED_BY) VALUES ('CICD','DEEPTANOY');
Insert into  SNOWFLAKE_CI_CD_POC.CI_CD_DEMO.SNOWFLAKE_CI_CD_DEMO11 (JOB_NM,CREATED_BY) VALUES ('CICD','TANOY');
Insert into  SNOWFLAKE_CI_CD_POC.CI_CD_DEMO.SNOWFLAKE_CI_CD_DEMO11 (JOB_NM,CREATED_BY) VALUESSS ('CICD','DEEP');
