name: snowflake-devops-demo-deloittena

# Controls when the action will run. 
on:
  push:
    branches:
      - SF_Deloittena
    paths:
    - 'Scripts/**'
    - 'Scripts/Stored Proc/**'
    - 'Scripts/Inserts/**'
    - 'Scripts/DDL/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run schemachange
        env:
          DELOITTENA_ACCOUNT: ${{ secrets.DELOITTENA_ACCOUNT }}
          DELOITTENA_USERNAME: ${{ secrets.DELOITTENA_USERNAME }}
          DELOITTENA_ROLE: ${{ secrets.DELOITTENA_ROLE }}
          DELOITTENA_WAREHOUSE: ${{ secrets.DELOITTENA_WAREHOUSE }}
          DELOITTENA_DATABASE: ${{ secrets.DELOITTENA_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.DELOITTENA_PASSWORD }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/Scripts** -a $DELOITTENA_ACCOUNT -u $DELOITTENA_USERNAME -r $DELOITTENA_ROLE -w $DELOITTENA_WAREHOUSE -d $AZURE_SF_DATABASE -c $DELOITTENA_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
